### ISSUE TITLE
IntuneMAM SDK not compatible with xcode 13 beta4

### ISSUE THREAD

**Issue by Prithvijutur** [msintuneappsdk/ms-intune-app-sdk-ios#195]
IntuneMAM SDK does not seem to be compatible with xcode 13

**To Reproduce**
1. Create a blank project
2.  Link IntuneMAMSwift.xcframework and IntuneMAMSwiftStub.xcframework to your target: Drag IntuneMAMSwift.xcframework and IntuneMAMSwiftStub.xcframework to the Frameworks, Libraries, and Embedded Content list of the project target
3. Add the IntuneMAMResources.bundle resource bundle to the project by dragging the resource bundle under Copy Bundle Resources within Build Phases.
4. Import using`import IntuneMAMSwift`

Expected behavior: The build running successfully
<img width="977" alt="Screen Shot 2021-08-18 at 6 15 39 PM" src="https://user-images.githubusercontent.com/3957837/129992188-fdad32e3-9e56-4678-b0ab-cbd024f85946.png">

Compiled with xcode13 beta4
Running on Simulator (iPhone 12, iOS 14.5)

**Intune App SDK for iOS (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
14.6.2
- What platform is your app based in (native, Xamarin based, Cordova, etc)?
Native
- For errors during build, does the app build without Intune SDK integration?
Yes
- For errors post build, does the app launch without being Intune SDK integrated?
- Who is the customer?
Box Inc
- Do you see a trend with it only being reproduced on a specific device?
No

Build Log: https://gist.github.com/Prithvijutur/2bdd59304ac480871b3316b03b562ef8
No issues building with xcode 12.5

**Comment by vigavadi** [comment]
@Prithvijutur Thanks for reaching out. Can you remove IntuneMAMResources.bundle and see if it builds fine?

**Comment by Prithvijutur** [comment]
@vigavadi IntuneMAMResources.bundle does not make a difference. https://github.com/Prithvijutur/intune

**Comment by vigavadi** [comment]
@Prithvijutur Thanks for linking the repo. I checked it out and there are a couple of things you might have to change:
1. I see the xcframework have been added to both "Link with libraries" and "Embedded Framework" phases. Can you remove them for the first one.
<img width="683" alt="Screen Shot 2021-08-20 at 9 49 09 AM" src="https://user-images.githubusercontent.com/62442249/130246817-a5b728b9-dae8-410b-95e9-34648526be4d.png">

2. I see the IntuneMAMResources.bundle still in the project. It shouldn't make a difference since I see it isn't  linked  anymore but, you can remove it altogether to avoid any issues.
<img width="268" alt="Screen Shot 2021-08-20 at 9 49 19 AM" src="https://user-images.githubusercontent.com/62442249/130247062-dabeaaf8-5042-4c42-9b8b-b07126fc7e9d.png">

Also, I noticed that you don't have the Intune xcframeworks in your project. You might want to have those copied in your project and drag it from there to your "Embedded Frameworks"

Let me know if these steps work for you.

**Comment by Prithvijutur** [comment]
Thanks @vigavadi Updated the repo with above. 
I rebuilt with xcode13 beta 5 and see an updated error message. What version of swift was used to build the xcframework? 
<img width="1506" alt="Screen Shot 2021-08-20 at 9 03 20 AM" src="https://user-images.githubusercontent.com/3957837/130261495-61a8aed5-2a87-4187-8fe4-7031a661564e.png">

**Comment by vigavadi** [comment]
@Prithvijutur Glad to know the previous error is resolved. The warnings that you are seeing now is because these IntuneMAM binaries are built on Xcode 12. We will be releasing support for Xcode 13 when Apple releases an official version. 
Meanwhile, this should unblock you from testing.  Let me know if you see any other issues.

**Comment by Prithvijutur** [comment]
@vigavadi Its a warning at compile time but error as runtime as the the binaries are incompatible, so testing is still blocked. Apple usually releases the official version the same time as the OS upgrade. Are you able to provide SDK users with a beta version built on xcode13 so we can test this ahead of the iOS upgrade?

**Comment by Prithvijutur** [comment]
Hi @vigavadi We spoke to Jamie Silvestri from Microsoft last week and were told that we could get a beta build if it helped with testing. Wanted to check with you if you were waiting on a sample app or are able to provide the beta build for testing. (Our main box application still fails on importing intunemamswift.)

**Comment by vigavadi** [comment]
@Prithvijutur Yeah I was waiting on the sample app. I'll check about the beta build and get back to you on this.

**Comment by vigavadi** [comment]
@Prithvijutur We have released 15.0.0 which supports Xcode 13 builds. Could you try it out and let us know if you still see issues?

**Comment by Prithvijutur** [comment]
@vigavadi Works, thank you!
