### ISSUE TITLE
App crashes in background when device is locked

### ISSUE THREAD

**Issue by yurarodionov** [msintuneappsdk/ms-intune-app-sdk-ios#85]
App crashes in background when user locks device and leave it for some time
=======

We are strugling to release new app version for Intune since we encounter a lot of crash reports on App Store Connect when test on TestFlight. All our attempts to resolve it failed. I was advised by Microsoft Support to open ticket here.

**To Reproduce**
1. Lock device
2. Wait for a few hours
3. Unlock device
4. iOS popups message that app crashed

**Expected behavior:**
No crashes when app in background
**Devices**
Happens on all devices

**Intune App SDK for iOS**
- SDK version: 9.0.11; bundle version: 181207.1,
- ADAL 2.6.5
- We have non-Intune app which has the same code base and it doesn't crash.
- Crashes happens on all devices.

**Additional context:**
1. We use Xcode 10.1 for distribution since we don't support Xcode 11 yet.
2. A few weeks ago it was identified that there is MaxFileProtectionLevel setting. We set NSFileProtectionCompleteUntilFirstUserAuthentication. The crash rate decreased but crashes still appear.
3. App supports a few background modes: remote notification, background fetch, VoIP, Audio.
4. I'm not able to share crashes stack trace. When I download report from App Store Connect I see feedback.json file only. Those crashes don't appear in Xcode organiser. I believe this is due to some Apple issue: https://forums.developer.apple.com/thread/127783

**Comment by Kyle-Reis** [comment]
Hey @yurarodionov, those versions of the Intune and ADAL SDKs are pretty old, and these crashed could be caused by bugs that have been addressed in newer releases, or by compatibility issues introduced with new versions of iOS. Could you please update to current releases and let us know if you continue to see this issue?

**Comment by Kyle-Reis** [comment]
Hi @yurarodionov, checking in to see if you're still experiencing this issue.

**Comment by Kyle-Reis** [comment]
Hey @yurarodionov, checking in one more time before closing out this issue. Did upgrading Intune and ADAL address this issue?

**Comment by yurarodionov** [comment]
Hi Kyle, 

the issue still happens but not so often than it was happening with the older SDKs version.

Let's keep it for a while

**Comment by Kyle-Reis** [comment]
Thanks @yurarodionov, are you still setting MaxFileProtectionLevel to NSFileProtectionCompleteUntilFirstUserAuthentication with the latest SDK?

**Comment by Kyle-Reis** [comment]
Hi @yurarodionov, checking in to see if you are still seeing this issue?

**Comment by Kyle-Reis** [comment]
Closing out this issue due to inactivity. Please reopen if you're still seeing this problem.
